---
title: 游땕 "Relaci칩n entre la felicidad y el 칤ndice democr치tico en 164 pa칤ses." 游땕
format: revealjs
editor: visual
---

## Descripci칩n:

Los datos empleados en este trabajo provienen de "WHR-Happiness Score Dataset" y el "칈ndice de democracia" de la Unidad de Inteligencia de The Economist.

El cuestionario"WHR-Happiness Score Dataset" es elaborado anualmente desde 2005 por la "[World Happiness Report](https://worldhappiness.report/)" y extra칤do de la web Gapminder.org (con la licencia internacional Creative Commons Attribution 4.0.). El "[칈ndice de democracia](https://es.wikipedia.org/wiki/%C3%8Dndice_de_democracia)" es una clasificaci칩n hecha por la Unidad de Inteligencia de The Economist, a trav칠s de la cual se pretende determinar el rango de democracia en 167 pa칤ses.

## An치lisis exploratorio:

Ya que durante el an치lisis exploratorio de los datos del informe "World Happiness Report" se ha encuentrado que para los pa칤ses menos democr치ticos no hay datos suficientes se ha considerado que la alternativa m치s interesante es considerar otras fuentes alternativas de datos y analizar otros indicadores relacionas. Es por ello que se ha considerado interesante cruzar el "World Happiness Report" con el "칈ndice de democracia".

## Cruce de datos:

Al cruzar los datos del informe internacional "World Happiness Report" de la Red de Soluciones para el Desarrollo Sostenible con los resultados del "칈ndice de Democracia" de la Unidad de Inteligencia de The Economist, podemos identificar una relaci칩n interesante entre la felicidad y el nivel de democracia en diferentes pa칤ses.

## An치lisis:

Al analizar ambos conjuntos de datos, es posible observar una tendencia general de que los pa칤ses con niveles m치s altos de democracia tienden a tener mayores niveles de felicidad. Esto puede atribuirse a varios factores relacionados:

-   Relaci칩n entre democracia y participaci칩n ciudadana.

-   Transparencia y la rendici칩n de cuentas.

-    Derechos civiles y pol칤ticos

## 쯉esgo?:

Probablemente haya aqu칤 un sesgo cultural al observar estos datos desde una perspectiva occidental y liberal, ya que la persona que ha elaborado este informe opina que la democracia proporciona una plataforma para la participaci칩n y la expresi칩n de opiniones individuales. Esta participaci칩n ciudadana activa puede llevar a una mayor sensaci칩n de empoderamiento y satisfacci칩n con el sistema pol칤tico, lo que a su vez contribuye a la felicidad individual y colectiva.

## Gr치fico:

```{r}

# Cargar archivo CSV - 춰춰춰IMPORTANTE: CAMBIA LA RUTA PARA QUE COINCIDA CON LA DE TU PC!!! 
data <- read.csv("/cloud/project/Datos/democratic-hapiness.csv")

# Instalar y cargar las bibliotecas necesarias
install.packages("ggplot2")
library(ggplot2)
install.packages("plotly")
library(plotly)
    
# Crear el gr치fico de dispersi칩n interactivo con etiquetas emergentes
plot <- plot_ly(data, x = ~score, y = ~media, text = ~country, type = "scatter", mode = "markers")

# Personalizar el gr치fico
plot <- plot %>% layout(xaxis = list(title = "Democracia"), yaxis = list(title = "Felicidad"), title = "Relaci칩n entre Felicidad y Democracia")

# Mostrar el gr치fico interactivo
plot

```

## Conclusi칩n:

En resumen, al cruzar los datos del informe "World Happiness Report" con los resultados del 칤ndice de democracia, se observa una relaci칩n positiva entre la felicidad y el nivel de democracia en los pa칤ses.

## 
