---
title: "M7 RETO 2."
output: html_document
date: "2023-05-19"
---

## Proyecto-Ciencia-de-Datos-UB

```{r}

## CARGAMOS BBDD ORIGINAL

# Instalar el paquete readr si no está instalado
install.packages("readr")
# Cargar el paquete readr
library(readr)

# Cargar archivo CSV (la fusión de "WHR-Happiness Score Dataset" con el "Índice de Democracia" ya se ha realizado con el software de ofimática Open Office)
data <- read.csv("hapiscore_whr_democracy_index2022.csv")

# Visualizar los primeros registros del archivo
head(data)

```
```{r}

## FORMATEAMOS DATOS PERDIDOS

# Reemplazar valores vacíos con NA a partir de la columna 4 hasta la última
data[data == ""] <- NA

# Reemplazar los NA por la media de los valores no NA a partir de la columna 4 hasta la última
data[, 4:ncol(data)] <- t(apply(data[, 4:ncol(data)], 1, function(x) {
  nas <- is.na(x)
  if (sum(nas) > 0) {
    x[nas] <- mean(x[!nas], na.rm = TRUE)
  }
  return(x)
}))

# Visualizar los primeros registros del archivo
head(data)

```

```{r}

## CALCULAMOS MEDIA DE LOS RESULTADOS DE INDICE FELICIDAD DE CADA PAÍS (2005-2022)

# Calcular la media 
data$media <- rowMeans(data[,4:ncol(data)])

# Imprimir el dataframe resultante
print(data)

```

```{r}

## GENERAMOS EL DATA FRAME FINAL CON LOS PAÍSES Y LAS 2 VARIABLES QUE NOS INTERESAN PARA NUESTRO ANÁLISIS

# Instalar el paquete tibble y dplyr si no está instalado
install.packages("tibble")
install.packages("dplyr")

# Cargar el paquete tibble
library(tibble)
# Cargar el paquete dplyr
library(dplyr)

# Convertir a 0 los valores NA de la columna "score" (se considera que no obtener una puntuación es indicador de nula democracia, aunque puede ser un sesgo a revisar en un futuro)
data$score <- ifelse(is.na(data$score), 0, data$score)

# Crear un nuevo dataframe con el índice y las columnas 1 (país), 2 (puntuación democrática), y última columna (media puntuación felicidad)
df <- data %>%
  select(1, 2, last_col())

# Guardar el data frame como un archivo CSV
write.csv(df, "democratic-hapiness.csv", row.names = FALSE)

# Imprimir el dataframe resultante
print(df)

```

```{r}

## SUMARIZAMOS EL DATA FRAME PARA HACERNOS UNA IDEA DE LOS RESULTADOS

# Cargar el paquete dplyr
library(dplyr)

# Sumarizar el data frame
resumen <- df %>%
  summarize(
    promedio_democracia = mean(score),
    max_democracia = max(score),
    min_democracia = min(score),
    promedio_happiness = mean(media),
    max_happiness = max(media),
    min_happiness = min(media)
  )

# Imprimir el resumen
print(resumen)

```

```{r}

## GENERAMOS UN DATA FRAME ALTERNATIVO CON LOS 10 PAISES MÁS ALTOS Y LOS 10 MÁS BAJOS EN LA PUNTUACIÓN DE FELICIDAD 

library(dplyr)

n <- 10  # Número de puntuaciones a seleccionar

top_scores <- df %>% top_n(n, wt = media)  # Las 10 puntuaciones más altas
bottom_scores <- df %>% top_n(-n, wt = media)  # Las 10 puntuaciones más bajas

# Combinar los resultados en un nuevo data frame
df2 <- rbind(top_scores, bottom_scores)

# Imprimir el df
print(df2)

# Guardar el data frame como un archivo CSV
write.csv(df2, "top-low-democratic-hapiness.csv", row.names = FALSE)

```
